'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3607
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RM_Manager.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property CDorDVD() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CDorDVD", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property CDorDVDwDrive() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CDorDVDwDrive", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property DNARROW() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("DNARROW", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This feature is not available for the freeware version..
        '''</summary>
        Friend ReadOnly Property en_FeatureNotAvailable() As String
            Get
                Return ResourceManager.GetString("en_FeatureNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to My Removable Media.
        '''</summary>
        Friend ReadOnly Property en_MyRemovableMedia() As String
            Get
                Return ResourceManager.GetString("en_MyRemovableMedia", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property FloppyBlue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FloppyBlue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property FloppyRed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FloppyRed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property FloppywDrive() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FloppywDrive", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property FolderClose() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("FolderClose", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property jigsaw() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("jigsaw", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property PenDrive() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PenDrive", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Search_tiny() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_tiny", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UPARROW() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("UPARROW", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property VentusRMM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VentusRMM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
